export const ORIGIN_PRODUCT_EXPERIENCE_CONTRACT = {
  version: "0.1",
  productName: "ORIGIN",
  orchestrationEngineName: "ACOS 2.0",
  releaseStrategy: "personal-first",
  finalGoal: "world-class-ai-agent-service",
  qualityGoal: {
    target: "highest-verified-deliverable-quality",
    unsupportedWorldBestClaimAllowed: false,
    evaluationDimensions: [
      "factual-accuracy",
      "goal-and-instruction-fit",
      "completeness",
      "practical-usability",
      "evidence-and-verifiability",
      "design-quality",
      "cross-device-quality",
    ],
    comparisonRequired: true,
    humanAcceptanceRequired: true,
  },
  purpose: [
    "understand-the-users-real-goal",
    "identify-unspoken-information-needed-to-achieve-the-goal",
    "deliver-useful-information-data-risks-and-next-actions-beyond-the-literal-request",
    "select-the-best-eligible-ai-for-the-task",
    "use-specialist-ai-when-it-materially-improves-the-result",
    "coordinate-multiple-independent-ais-when-useful-not-for-display",
    "research-compare-review-and-synthesize",
    "deliver-a-truthful-actionable-result",
  ],
  orchestrationStages: [
    "understand-goal",
    "identify-needed-context-data-and-deliverables",
    "classify-task",
    "select-safe-free-ai",
    "execute",
    "collect-evidence",
    "independent-review-when-required",
    "synthesize",
    "present-truthfully",
  ],
  answerPresentation: {
    defaultLanguage: "ja",
    requiredOrder: [
      "conclusion",
      "answer",
      "evidence",
      "verification-status",
      "limitations",
      "next-actions",
    ],
    optionalWhenUseful: [
      "comparison",
      "forecast",
      "advice",
      "chart",
      "illustration",
      "document",
      "presentation",
      "proposal",
      "talk-script",
      "image",
      "application",
      "website",
      "social-post",
      "spreadsheet",
      "downloadable-artifact",
    ],
    progressiveDisclosure: true,
    technicalDetailsCollapsedByDefault: true,
  },
  design: {
    principles: [
      "calm-hierarchy",
      "single-clear-primary-action",
      "dark-first",
      "responsive",
      "accessibility-first",
      "truthful-system-status",
      "cross-device-equivalence",
      "device-appropriate-information-density",
    ],
    targetDevices: ["smartphone", "tablet", "desktop"],
    inspirationQuality: ["Apple", "Linear", "Notion", "Figma"],
    imitateThirdPartyBranding: false,
  },
  evolution: {
    integrationBoundary: "provider-adapter",
    capabilityCatalogExtensible: true,
    outputCatalogExtensible: true,
    interactionModes: ["conversation", "deliverable", "agent-workflow"],
    routingEvidence: ["capability", "safety", "cost", "availability", "quality-evidence"],
    coreRewriteRequiredForNewAi: false,
    uiRewriteRequiredForNewAi: false,
    automaticActivation: false,
    explicitStableModelIdsOnly: true,
    lifecycleEvidenceRequired: true,
  },
  invariants: {
    providerNeutralCore: true,
    freeOnly: true,
    maxEstimatedCostUsd: 0,
    automaticPaidFallback: false,
    credentialsInServerEnvironmentOnly: true,
    fabricatedDataAllowed: false,
    unimplementedFeaturesPresentedAsAvailable: false,
    unexecutedReviewPresentedAsVerified: false,
    unsupportedQualityClaimsAllowed: false,
  },
} as const;
