export const ORIGIN_PRODUCT_EXPERIENCE_CONTRACT = {
  version: "0.1",
  productName: "ORIGIN",
  orchestrationEngineName: "ACOS 2.0",
  releaseStrategy: "personal-first",
  finalGoal: "world-class-ai-orchestration-os",
  purpose: [
    "understand-the-users-real-goal",
    "select-the-best-eligible-ai-for-the-task",
    "coordinate-multiple-independent-ais-when-useful",
    "research-compare-review-and-synthesize",
    "deliver-a-truthful-actionable-result",
  ],
  orchestrationStages: [
    "understand-goal",
    "classify-task",
    "select-safe-free-ai",
    "execute",
    "collect-evidence",
    "independent-review-when-required",
    "synthesize",
    "present-truthfully",
  ],
  answerPresentation: {
    defaultLanguage: "ja",
    requiredOrder: [
      "conclusion",
      "answer",
      "evidence",
      "verification-status",
      "limitations",
      "next-actions",
    ],
    optionalWhenUseful: [
      "comparison",
      "forecast",
      "advice",
      "chart",
      "illustration",
      "downloadable-artifact",
    ],
    progressiveDisclosure: true,
    technicalDetailsCollapsedByDefault: true,
  },
  design: {
    principles: [
      "calm-hierarchy",
      "single-clear-primary-action",
      "dark-first",
      "responsive",
      "accessibility-first",
      "truthful-system-status",
    ],
    inspirationQuality: ["Apple", "Linear", "Notion", "Figma"],
    imitateThirdPartyBranding: false,
  },
  invariants: {
    providerNeutralCore: true,
    freeOnly: true,
    maxEstimatedCostUsd: 0,
    automaticPaidFallback: false,
    credentialsInServerEnvironmentOnly: true,
    fabricatedDataAllowed: false,
    unimplementedFeaturesPresentedAsAvailable: false,
    unexecutedReviewPresentedAsVerified: false,
    unsupportedQualityClaimsAllowed: false,
  },
} as const;
