import {
  ORIGIN_GOOGLE_AI_STUDIO_FREE_MODEL,
  ORIGIN_GROQ_FREE_MODEL,
  ORIGIN_OPENROUTER_FREE_MODEL,
  type OriginExecutionPlan,
  type OriginProviderDataPolicy,
} from "../lib/orchestration/OriginExecutionPolicy.js";
import { sanitizePreEgress, sanitizePreEgressPayload } from "../services/securitySanitizer.js";

export interface OriginChatMessage { role: "user" | "ai" | "assistant" | "model"; content: string; }
export interface OriginProviderExecutionRequest { plan: OriginExecutionPlan; messages: OriginChatMessage[]; systemInstruction: string; }
export interface OriginProviderRoutingEvidence { requestedModel: string; servedModel: string; strategy: string; provider: string; region?: string; attempt: 1; fallbackUsed: boolean; }
export interface OriginProviderExecutionResult { text: string; actualCostUsd: 0; providerDataPolicy: OriginProviderDataPolicy; routingEvidence: OriginProviderRoutingEvidence; usage: { promptTokens?: number; completionTokens?: number; totalTokens?: number; costUsd: 0 }; }
export type OriginProviderErrorCode = "PROVIDER_NOT_CONFIGURED" | "PROVIDER_POLICY_VIOLATION" | "PROVIDER_COST_UNVERIFIED" | "PROVIDER_ROUTING_UNVERIFIED" | "PROVIDER_RATE_LIMITED" | "PROVIDER_UNAVAILABLE" | "PROVIDER_TIMEOUT" | "PROVIDER_INVALID_RESPONSE" | "PROVIDER_INTERNAL_ERROR";
export interface OriginProviderDiagnostic { upstreamStatus?: number; upstreamErrorType?: string; transportFailure?: "timeout" | "network"; }
export class OriginProviderError extends Error { constructor(public readonly code: OriginProviderErrorCode, message: string, public readonly status: number, public readonly retryable: boolean, public readonly retryAfterSeconds?: number, public readonly diagnostic?: OriginProviderDiagnostic) { super(message); this.name = "OriginProviderError"; } }
export type OriginFetch = typeof fetch;
const SILENT_RETRY_DELAYS_MS = [200, 500, 1000] as const;
const PROVIDER_ATTEMPT_TIMEOUT_MS = 6000;
const PROVIDER_COOLDOWN_MS = 15_000;
const MAX_COMPLETION_SEGMENTS = 3;
export const ALLOWED_ZERO_COST_PROVIDERS = ["openrouter", "groq", "google-gemini"] as const;
export type AllowedZeroCostProvider = typeof ALLOWED_ZERO_COST_PROVIDERS[number];
export const ALLOWED_ZERO_COST_MODELS = { openrouter: [ORIGIN_OPENROUTER_FREE_MODEL] as const, groq: [ORIGIN_GROQ_FREE_MODEL] as const, "google-gemini": [ORIGIN_GOOGLE_AI_STUDIO_FREE_MODEL] as const } as const;
const PROVIDER_ID_BY_LABEL: Record<string, AllowedZeroCostProvider> = { OpenRouter: "openrouter", Groq: "groq", "Google AI Studio": "google-gemini", "google-ai-studio-free": "google-gemini", "openrouter-free": "openrouter", "groq-free": "groq", "google-gemini": "google-gemini" };
const cooldownUntil: Partial<Record<AllowedZeroCostProvider, number>> = {};
function now() { return Date.now(); }
function markCooldown(p: AllowedZeroCostProvider) { cooldownUntil[p] = now() + PROVIDER_COOLDOWN_MS; }
function cooling(p: AllowedZeroCostProvider) { const until = cooldownUntil[p] ?? 0; if (until <= now()) { delete cooldownUntil[p]; return false; } return true; }
function providerId(v: unknown): AllowedZeroCostProvider | null { if (typeof v !== "string") return null; return PROVIDER_ID_BY_LABEL[v] ?? (ALLOWED_ZERO_COST_PROVIDERS.includes(v as AllowedZeroCostProvider) ? v as AllowedZeroCostProvider : null); }
function allowedModel(p: AllowedZeroCostProvider, m: unknown): m is string { return typeof m === "string" && (ALLOWED_ZERO_COST_MODELS[p] as readonly string[]).includes(m); }
function fail(message: string, code: OriginProviderErrorCode = "PROVIDER_POLICY_VIOLATION"): never { throw new OriginProviderError(code, message, 502, false); }
function assertZero(v: unknown, field: string): asserts v is 0 { if (typeof v !== "number" || !Number.isFinite(v) || v < 0 || Math.abs(v) > Number.EPSILON) fail(`${field} が$0ポリシーを満たしません。`, "PROVIDER_COST_UNVERIFIED"); }
export function assertOriginZeroCostExecutionResult(result: OriginProviderExecutionResult, expectedModel?: string, expectedProvider?: string): void {
  if (!result || typeof result !== "object") fail("無料AIの実行結果を検証できません。", "PROVIDER_COST_UNVERIFIED");
  assertZero(result.actualCostUsd, "actualCostUsd"); assertZero(result.usage?.costUsd, "usage.costUsd");
  const e = result.routingEvidence; if (!e) fail("実行証跡がありません。", "PROVIDER_ROUTING_UNVERIFIED");
  const p = providerId(e.provider); if (!p || !allowedModel(p, e.servedModel)) fail("許可された無料Provider/Modelの実行証跡を確認できません。", "PROVIDER_ROUTING_UNVERIFIED");
  if (expectedModel && e.requestedModel !== expectedModel) fail("選択モデルと要求モデルが一致しません。", "PROVIDER_ROUTING_UNVERIFIED");
  if (e.attempt !== 1) fail("不正な実行試行番号です。", "PROVIDER_ROUTING_UNVERIFIED");
  if (e.fallbackUsed) { if (e.strategy !== "zero-cost-failover") fail("Fallback証跡が不正です。", "PROVIDER_ROUTING_UNVERIFIED"); }
  else { if (e.strategy !== "adaptive-primary" || e.requestedModel !== e.servedModel) fail("Primary証跡が不正です。", "PROVIDER_ROUTING_UNVERIFIED"); if (expectedProvider && providerId(expectedProvider) !== p) fail("選択Providerと実行Providerが一致しません。", "PROVIDER_ROUTING_UNVERIFIED"); }
}
export function originCompletionTokenBudget(taskType: OriginExecutionPlan["taskType"]): number { switch (taskType) { case "implementation": case "documentation": return 2400; case "research": case "review": case "architecture": case "security": case "current-information": return 1800; default: return 1200; } }
function normalizeMessages(messages: OriginChatMessage[], systemInstruction: string) { return [{ role: "system", content: sanitizePreEgress(systemInstruction) }, ...messages.map(m => ({ role: m.role === "user" ? "user" : "assistant", content: sanitizePreEgress(m.content) }))]; }
function textOf(content: unknown): string { if (typeof content === "string") return content.trim(); if (!Array.isArray(content)) return ""; return content.filter((x: any) => x && typeof x.text === "string").map((x: any) => x.text.trim()).filter(Boolean).join("\n\n").trim(); }
function retryAfter(v: string | null): number | undefined { if (!v) return undefined; const n = Number(v); if (Number.isFinite(n) && n > 0) return Math.ceil(n); const t = Date.parse(v); return Number.isFinite(t) ? Math.max(1, Math.ceil((t - Date.now()) / 1000)) : undefined; }
function httpError(status: number, retryAfterSeconds?: number): OriginProviderError { const d={upstreamStatus:status}; if(status===401)return new OriginProviderError("PROVIDER_NOT_CONFIGURED","Provider認証情報を確認できません。",401,false,undefined,d); if(status===402)return new OriginProviderError("PROVIDER_POLICY_VIOLATION","無料実行として確認できない課金状態です。",502,false,undefined,d); if(status===429)return new OriginProviderError("PROVIDER_RATE_LIMITED","無料AIの利用上限に達しました。",429,true,retryAfterSeconds,d); if(status===408||status===504)return new OriginProviderError("PROVIDER_TIMEOUT","無料AIがタイムアウトしました。",504,true,undefined,d); if([403,404,500,502,503].includes(status))return new OriginProviderError("PROVIDER_UNAVAILABLE","無料AIを現在利用できません。",503,true,undefined,d); return new OriginProviderError("PROVIDER_INTERNAL_ERROR","無料AIの処理に失敗しました。",500,status>=500,undefined,d); }
async function readJson(r: Response): Promise<any> { try{return await r.json();}catch{throw new OriginProviderError("PROVIDER_INVALID_RESPONSE","無料AIから有効な応答を取得できません。",502,true);} }
async function fetchRetry(fetchImpl: OriginFetch,input: RequestInfo|URL,init: RequestInit): Promise<Response> { let last:unknown; for(let i=0;i<=SILENT_RETRY_DELAYS_MS.length;i++){if(i)await new Promise(r=>setTimeout(r,SILENT_RETRY_DELAYS_MS[i-1]));const c=new AbortController();const timer=setTimeout(()=>c.abort(),PROVIDER_ATTEMPT_TIMEOUT_MS);try{const r=await fetchImpl(input,{...init,signal:c.signal});if(r.status===429)throw httpError(429,retryAfter(r.headers.get("Retry-After")));if(![408,500,502,503,504].includes(r.status)||i===SILENT_RETRY_DELAYS_MS.length)return r;last=httpError(r.status,retryAfter(r.headers.get("Retry-After")));}catch(e){if(e instanceof OriginProviderError)throw e;last=e;if(i===SILENT_RETRY_DELAYS_MS.length)break;}finally{clearTimeout(timer);}}if(last instanceof OriginProviderError)throw last;throw new OriginProviderError("PROVIDER_TIMEOUT","無料AIとの通信に失敗しました。",504,true,undefined,{transportFailure:"timeout"}); }
function validatePlan(plan: OriginExecutionPlan) { const p=providerId(plan.providerId); if(!plan.freeOnly||plan.estimatedCostUsd!==0||plan.providerDataPolicy.allowProviderFallbacks!==true||plan.providerDataPolicy.dataCollection!=="deny"||!p||!allowedModel(p,plan.modelId))throw new OriginProviderError("PROVIDER_POLICY_VIOLATION","0ドル固定ポリシーに適合しない実行計画です。",400,false); }
function evidence(request: OriginProviderExecutionRequest,p:AllowedZeroCostProvider,served:string):OriginProviderRoutingEvidence{const primary=providerId(request.plan.providerId)===p;return{requestedModel:request.plan.modelId,servedModel:served,strategy:primary?"adaptive-primary":"zero-cost-failover",provider:p==="openrouter"?"OpenRouter":p==="groq"?"Groq":"Google AI Studio",attempt:1,fallbackUsed:!primary};}
async function executeOpenRouter(request:OriginProviderExecutionRequest,key:string,fetchImpl:OriginFetch,p:AllowedZeroCostProvider):Promise<OriginProviderExecutionResult>{let msgs=normalizeMessages(request.messages,request.systemInstruction),out="",pt=0,ct=0,tt=0;for(let i=0;i<MAX_COMPLETION_SEGMENTS;i++){const r=await fetchRetry(fetchImpl,"https://openrouter.ai/api/v1/chat/completions",{method:"POST",headers:{"Content-Type":"application/json",Authorization:`Bearer ${key}`,"HTTP-Referer":"https://myaispecials.ai.studio/","X-OpenRouter-Title":"ORIGIN Personal"},body:JSON.stringify(sanitizePreEgressPayload({model:request.plan.modelId,messages:msgs,max_tokens:originCompletionTokenBudget(request.plan.taskType),temperature:0.2,top_p:0.9,provider:{sort:"throughput",allow_fallbacks:true,data_collection:"deny"}}))});const d=await readJson(r);const err=d.choices?.[0]?.error?.metadata?.error_type??d.error?.metadata?.error_type;if(err==="rate_limit_exceeded")throw httpError(429);if(err==="timeout")throw httpError(504);if(["provider_overloaded","provider_unavailable"].includes(err))throw httpError(503);const served=d.model;if(!allowedModel(p,served))throw new OriginProviderError("PROVIDER_ROUTING_UNVERIFIED","OpenRouterの無料モデル証跡を確認できません。",502,false);const part=textOf(d.choices?.[0]?.message?.content);if(!part)throw new OriginProviderError("PROVIDER_INVALID_RESPONSE","OpenRouterから回答を取得できません。",502,true);out=out?`${out}\n\n${part}`:part;pt+=d.usage?.prompt_tokens??0;ct+=d.usage?.completion_tokens??0;tt+=d.usage?.total_tokens??0;assertZero(d.usage?.cost??0,"usage.cost");if(d.choices?.[0]?.finish_reason!=="length"||i===MAX_COMPLETION_SEGMENTS-1){const result={text:out,actualCostUsd:0 as const,providerDataPolicy:request.plan.providerDataPolicy,routingEvidence:evidence(request,p,served),usage:{promptTokens:pt,completionTokens:ct,totalTokens:tt,costUsd:0 as const}};assertOriginZeroCostExecutionResult(result,request.plan.modelId,request.plan.providerId);return result;}msgs=[...msgs,{role:"assistant",content:out},{role:"user",content:"前回の回答が途切れました。続きだけを返してください。"}];}throw new OriginProviderError("PROVIDER_INVALID_RESPONSE","回答を完了できませんでした。",502,true);}
async function executeGemini(request:OriginProviderExecutionRequest,key:string,fetchImpl:OriginFetch,p:AllowedZeroCostProvider):Promise<OriginProviderExecutionResult>{const url=`https://generativelanguage.googleapis.com/v1beta/models/${encodeURIComponent(request.plan.modelId)}:generateContent?key=${encodeURIComponent(key)}`;const body=sanitizePreEgressPayload({systemInstruction:{parts:[{text:sanitizePreEgress(request.systemInstruction)}]},contents:request.messages.map(m=>({role:m.role==="user"?"user":"model",parts:[{text:sanitizePreEgress(m.content)}]})),generationConfig:{maxOutputTokens:originCompletionTokenBudget(request.plan.taskType),temperature:0.2,topP:0.9}});const d=await readJson(await fetchRetry(fetchImpl,url,{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify(body)}));const out=textOf(d.candidates?.[0]?.content?.parts);if(!out)throw new OriginProviderError("PROVIDER_INVALID_RESPONSE","Geminiから回答を取得できません。",502,true);const result={text:out,actualCostUsd:0 as const,providerDataPolicy:request.plan.providerDataPolicy,routingEvidence:evidence(request,p,request.plan.modelId),usage:{costUsd:0 as const}};assertOriginZeroCostExecutionResult(result,request.plan.modelId,request.plan.providerId);return result;}
async function executeGroq(request:OriginProviderExecutionRequest,key:string,fetchImpl:OriginFetch,p:AllowedZeroCostProvider):Promise<OriginProviderExecutionResult>{const body=sanitizePreEgressPayload({model:request.plan.modelId,messages:normalizeMessages(request.messages,request.systemInstruction),max_tokens:originCompletionTokenBudget(request.plan.taskType),temperature:0.2,top_p:0.9});const d=await readJson(await fetchRetry(fetchImpl,"https://api.groq.com/openai/v1/chat/completions",{method:"POST",headers:{"Content-Type":"application/json",Authorization:`Bearer ${key}`},body:JSON.stringify(body)}));const out=textOf(d.choices?.[0]?.message?.content);if(!out)throw new OriginProviderError("PROVIDER_INVALID_RESPONSE","Groqから回答を取得できません。",502,true);const result={text:out,actualCostUsd:0 as const,providerDataPolicy:request.plan.providerDataPolicy,routingEvidence:evidence(request,p,request.plan.modelId),usage:{promptTokens:d.usage?.prompt_tokens,completionTokens:d.usage?.completion_tokens,totalTokens:d.usage?.total_tokens,costUsd:0 as const}};assertOriginZeroCostExecutionResult(result,request.plan.modelId,request.plan.providerId);return result;}
function canFailover(e:unknown):e is OriginProviderError{return e instanceof OriginProviderError&&e.retryable&&(e.code==="PROVIDER_RATE_LIMITED"||e.code==="PROVIDER_UNAVAILABLE"||e.code==="PROVIDER_TIMEOUT"||e.code==="PROVIDER_INTERNAL_ERROR");}
async function runProvider(p:AllowedZeroCostProvider,request:OriginProviderExecutionRequest,env:NodeJS.ProcessEnv,fetchImpl:OriginFetch){if(cooling(p))return null;const key=p==="openrouter"?env.OPENROUTER_API_KEY:p==="google-gemini"?(env.GEMINI_API_KEY??env.GOOGLE_AI_STUDIO_API_KEY):env.GROQ_API_KEY;if(!key)return null;try{return p==="openrouter"?await executeOpenRouter(request,key,fetchImpl,p):p==="google-gemini"?await executeGemini(request,key,fetchImpl,p):await executeGroq(request,key,fetchImpl,p);}catch(e){if(e instanceof OriginProviderError&&e.retryable)markCooldown(p);throw e;}}
export async function executeOriginProvider(request:OriginProviderExecutionRequest,env:NodeJS.ProcessEnv=process.env,fetchImpl:OriginFetch=fetch):Promise<OriginProviderExecutionResult>{validatePlan(request.plan);const primary=providerId(request.plan.providerId)!;const order:AllowedZeroCostProvider[]=[primary,...ALLOWED_ZERO_COST_PROVIDERS.filter(p=>p!==primary)];const failures:OriginProviderError[]=[];for(const p of order){try{const result=await runProvider(p,request,env,fetchImpl);if(result)return result;}catch(e){if(!canFailover(e))throw e;failures.push(e);}}throw failures.at(-1)??new OriginProviderError("PROVIDER_UNAVAILABLE","利用可能な無料AIがありません。",503,true);}
