import {
  ORIGIN_GOOGLE_AI_STUDIO_FREE_MODEL,
  ORIGIN_GROQ_FREE_MODEL,
  ORIGIN_OPENROUTER_FREE_MODEL,
  type OriginExecutionPlan,
  type OriginProviderDataPolicy,
} from "../lib/orchestration/OriginExecutionPolicy.js";
import { sanitizePreEgress, sanitizePreEgressPayload } from "../services/securitySanitizer.js";
export interface OriginChatMessage { role: "user" | "ai" | "assistant" | "model"; content: string; }
export interface OriginProviderExecutionRequest { plan: OriginExecutionPlan; messages: OriginChatMessage[]; systemInstruction: string; }
export interface OriginProviderRoutingEvidence { requestedModel: string; servedModel: string; strategy: string; provider: string; region?: string; attempt: 1; fallbackUsed: boolean; }
export interface OriginProviderExecutionResult { text: string; actualCostUsd: 0; providerDataPolicy: OriginProviderDataPolicy; routingEvidence: OriginProviderRoutingEvidence; usage: { promptTokens?: number; completionTokens?: number; totalTokens?: number; costUsd: 0 }; }
export type OriginProviderErrorCode = "PROVIDER_NOT_CONFIGURED" | "PROVIDER_POLICY_VIOLATION" | "PROVIDER_COST_UNVERIFIED" | "PROVIDER_ROUTING_UNVERIFIED" | "PROVIDER_RATE_LIMITED" | "PROVIDER_UNAVAILABLE" | "PROVIDER_TIMEOUT" | "PROVIDER_INVALID_RESPONSE" | "PROVIDER_INTERNAL_ERROR";
export interface OriginProviderDiagnostic { upstreamStatus?: number; upstreamErrorType?: string; transportFailure?: "timeout" | "network"; }
export class OriginProviderError extends Error { constructor(public readonly code: OriginProviderErrorCode,message:string,public readonly status:number,public readonly retryable:boolean,public readonly retryAfterSeconds?:number,public readonly diagnostic?:OriginProviderDiagnostic){super(message);this.name="OriginProviderError";} }
export type OriginFetch = typeof fetch;
const RETRY=[200,500,1000] as const, TIMEOUT=6000, COOLDOWN=15000, MAX_SEGMENTS=3;
/** Production zero-cost execution is intentionally single-provider. Legacy provider identifiers remain exported only for compatibility. */
export const ALLOWED_ZERO_COST_PROVIDERS=["openrouter"] as const;
export type AllowedZeroCostProvider=typeof ALLOWED_ZERO_COST_PROVIDERS[number];
export const ALLOWED_ZERO_COST_MODELS={openrouter:[ORIGIN_OPENROUTER_FREE_MODEL] as const} as const;
const IDS:Record<string,AllowedZeroCostProvider>={OpenRouter:"openrouter","openrouter-free":"openrouter"};
const cooldown:Partial<Record<AllowedZeroCostProvider,number>>={};
const pid=(v:unknown):AllowedZeroCostProvider|null=>typeof v==="string"?(IDS[v]??(ALLOWED_ZERO_COST_PROVIDERS.includes(v as AllowedZeroCostProvider)?v as AllowedZeroCostProvider:null)):null;
const allowed=(p:AllowedZeroCostProvider,m:unknown):m is string=>typeof m==="string"&&(ALLOWED_ZERO_COST_MODELS[p] as readonly string[]).includes(m);
const mark=(p:AllowedZeroCostProvider)=>{cooldown[p]=Date.now()+COOLDOWN;};
const isCooling=(p:AllowedZeroCostProvider)=>{const t=cooldown[p]??0;if(t<=Date.now()){delete cooldown[p];return false;}return true;};
function fail(m:string,c:OriginProviderErrorCode="PROVIDER_POLICY_VIOLATION"):never{throw new OriginProviderError(c,m,502,false);}
function zero(v:unknown,f:string):asserts v is 0{if(typeof v!=="number"||!Number.isFinite(v)||v<0||Math.abs(v)>Number.EPSILON)fail(`${f} が$0ポリシーを満たしません。`,"PROVIDER_COST_UNVERIFIED");}
export function assertOriginZeroCostExecutionResult(r:OriginProviderExecutionResult,expectedModel?:string,expectedProvider?:string):void{if(!r||typeof r!=="object")fail("実行結果を検証できません。","PROVIDER_COST_UNVERIFIED");zero(r.actualCostUsd,"actualCostUsd");zero(r.usage?.costUsd,"usage.costUsd");const e=r.routingEvidence,p=pid(e?.provider);if(!e||!p||!allowed(p,e.servedModel))fail("許可された無料Provider/Modelの証跡を確認できません。","PROVIDER_ROUTING_UNVERIFIED");if(expectedModel&&e.requestedModel!==expectedModel)fail("要求モデルが一致しません。","PROVIDER_ROUTING_UNVERIFIED");if(e.attempt!==1)fail("不正な試行番号です。","PROVIDER_ROUTING_UNVERIFIED");if(e.fallbackUsed||e.strategy!=="adaptive-primary"||e.requestedModel!==e.servedModel)fail("Provider fallback またはPrimary証跡が不正です。","PROVIDER_ROUTING_UNVERIFIED");if(expectedProvider&&pid(expectedProvider)!==p)fail("Providerが一致しません。","PROVIDER_ROUTING_UNVERIFIED");}
export function originCompletionTokenBudget(t:OriginExecutionPlan["taskType"]):number{switch(t){case"implementation":case"documentation":return 2400;case"research":case"review":case"architecture":case"security":case"current-information":return 1800;default:return 1200;}}
const msgs=(m:OriginChatMessage[],s:string)=>[{role:"system",content:sanitizePreEgress(s)},...m.map(x=>({role:x.role==="user"?"user":"assistant",content:sanitizePreEgress(x.content)}))];
const text=(c:unknown):string=>typeof c==="string"?c.trim():Array.isArray(c)?c.filter((x:any)=>x&&typeof x.text==="string").map((x:any)=>x.text.trim()).filter(Boolean).join("\n\n").trim():"";
function mergeContinuation(previous:string,continuation:string):string{const left=previous.trimEnd(),right=continuation.trimStart();for(let n=Math.min(left.length,right.length,500);n>=20;n-=1)if(left.slice(-n)===right.slice(0,n))return `${left}${right.slice(n)}`.trim();const a=left.split("\n"),b=right.split("\n");while(b[0]?.trim()==="")b.shift();if(b[0]&&/^#{1,6}\s+/.test(b[0])&&a.some(x=>x.replace(/^(?:#{1,6}\s+|[-*+]\s+)/,"").toLocaleLowerCase()===b[0].replace(/^#{1,6}\s+/,"").replace(/[（(]\s*(?:続き|continued)\s*[）)]/i,"").toLocaleLowerCase()))b.shift();for(let n=Math.min(a.length,b.length,20);n>=1;n-=1){const aa=a.slice(-n).map(x=>x.trim().toLocaleLowerCase()),bb=b.slice(0,n).map(x=>x.trim().toLocaleLowerCase());if(aa.every(Boolean)&&aa.every((x,i)=>x===bb[i]))return[...a,...b.slice(n)].join("\n").trim();}return `${left}\n\n${right}`.trim();}
const retryAfter=(v:string|null)=>{if(!v)return undefined;const n=Number(v);if(Number.isFinite(n)&&n>0)return Math.ceil(n);const t=Date.parse(v);return Number.isFinite(t)?Math.max(1,Math.ceil((t-Date.now())/1000)):undefined;};
function http(status:number,ra?:number):OriginProviderError{const d={upstreamStatus:status};if(status===401)return new OriginProviderError("PROVIDER_NOT_CONFIGURED","Provider認証情報を確認できません。",401,false,undefined,d);if(status===402)return new OriginProviderError("PROVIDER_POLICY_VIOLATION","無料実行として確認できない課金状態です。",502,false,undefined,d);if(status===429)return new OriginProviderError("PROVIDER_RATE_LIMITED","無料AIの利用上限に達しました。",429,true,ra,d);if(status===408||status===504)return new OriginProviderError("PROVIDER_TIMEOUT","無料AIがタイムアウトしました。",504,true,undefined,d);return new OriginProviderError("PROVIDER_UNAVAILABLE","無料AIを現在利用できません。",503,true,undefined,d);}
async function json(r:Response){try{return await r.json();}catch{throw new OriginProviderError("PROVIDER_INVALID_RESPONSE","無料AIから有効な応答を取得できません。",502,true);}}
async function request(fetchImpl:OriginFetch,input:RequestInfo|URL,init:RequestInit):Promise<Response>{let last:unknown;for(let i=0;i<=RETRY.length;i++){if(i)await new Promise(r=>setTimeout(r,RETRY[i-1]));const c=new AbortController(),tm=setTimeout(()=>c.abort(),TIMEOUT);try{const r=await fetchImpl(input,{...init,signal:c.signal});if(r.status===429)throw http(429,retryAfter(r.headers.get("Retry-After")));if(![408,500,502,503,504].includes(r.status)||i===RETRY.length)return r;last=http(r.status,retryAfter(r.headers.get("Retry-After")));}catch(e){if(e instanceof OriginProviderError)throw e;last=e;if(i===RETRY.length)break;}finally{clearTimeout(tm);}}if(last instanceof OriginProviderError)throw last;throw new OriginProviderError("PROVIDER_TIMEOUT","無料AIとの通信に失敗しました。",504,true);}
function validate(plan:OriginExecutionPlan){const p=pid(plan.providerId);if(!plan.freeOnly||plan.estimatedCostUsd!==0||plan.providerDataPolicy.allowProviderFallbacks!==false||plan.providerDataPolicy.dataCollection!=="deny"||!p||!allowed(p,plan.modelId))throw new OriginProviderError("PROVIDER_POLICY_VIOLATION","0ドル固定ポリシーに適合しない実行計画です。",400,false);}
function evidence(req:OriginProviderExecutionRequest,p:AllowedZeroCostProvider,served:string):OriginProviderRoutingEvidence{return{requestedModel:req.plan.modelId,servedModel:served,strategy:"adaptive-primary",provider:"OpenRouter",attempt:1,fallbackUsed:false};}
async function openrouter(req:OriginProviderExecutionRequest,key:string,f:OriginFetch,p:AllowedZeroCostProvider):Promise<OriginProviderExecutionResult>{let mm=msgs(req.messages,req.systemInstruction),out="",pt=0,ct=0,tt=0;for(let i=0;i<MAX_SEGMENTS;i++){const r=await request(f,"https://openrouter.ai/api/v1/chat/completions",{method:"POST",headers:{"Content-Type":"application/json",Authorization:`Bearer ${key}`,"HTTP-Referer":"https://myaispecials.ai.studio/","X-OpenRouter-Title":"ORIGIN Personal"},body:JSON.stringify(sanitizePreEgressPayload({model:req.plan.modelId,messages:mm,max_tokens:originCompletionTokenBudget(req.plan.taskType),temperature:.2,top_p:.9,provider:{sort:"throughput",allow_fallbacks:false,data_collection:"deny"}}))});const d=await json(r),err=d.choices?.[0]?.error?.metadata?.error_type??d.error?.metadata?.error_type;if(err==="rate_limit_exceeded")throw http(429);if(err==="timeout")throw http(504);if(["provider_overloaded","provider_unavailable"].includes(err))throw new OriginProviderError("PROVIDER_UNAVAILABLE","無料AIを現在利用できません。",503,true,undefined,{upstreamErrorType:err});const served=d.model;if(!allowed(p,served))throw new OriginProviderError("PROVIDER_ROUTING_UNVERIFIED","OpenRouter無料モデルを確認できません。",502,false);const part=text(d.choices?.[0]?.message?.content);if(!part)throw new OriginProviderError("PROVIDER_INVALID_RESPONSE","OpenRouterから回答を取得できません。",502,true);out=out?mergeContinuation(out,part):part;pt+=d.usage?.prompt_tokens??0;ct+=d.usage?.completion_tokens??0;tt+=d.usage?.total_tokens??0;zero(d.usage?.cost,"usage.cost");if(d.choices?.[0]?.finish_reason!=="length"){const result={text:out,actualCostUsd:0 as const,providerDataPolicy:req.plan.providerDataPolicy,routingEvidence:evidence(req,p,served),usage:{promptTokens:pt,completionTokens:ct,totalTokens:tt,costUsd:0 as const}};assertOriginZeroCostExecutionResult(result,req.plan.modelId,req.plan.providerId);return result;}if(i===MAX_SEGMENTS-1)throw new OriginProviderError("PROVIDER_INVALID_RESPONSE","回答を完了できませんでした。",502,true);mm=[...msgs(req.messages,req.systemInstruction),{role:"assistant",content:out},{role:"user",content:"直前の回答が出力上限で途切れました。途切れた箇所から最後まで不足部分だけを続けてください。"}];}throw new OriginProviderError("PROVIDER_INVALID_RESPONSE","回答を完了できませんでした。",502,true);}
const failover=(e:unknown):e is OriginProviderError=>e instanceof OriginProviderError&&e.retryable&&["PROVIDER_RATE_LIMITED","PROVIDER_UNAVAILABLE","PROVIDER_TIMEOUT","PROVIDER_INTERNAL_ERROR"].includes(e.code);
export async function executeOriginProvider(request:OriginProviderExecutionRequest,env:NodeJS.ProcessEnv=process.env,fetchImpl:OriginFetch=fetch):Promise<OriginProviderExecutionResult>{validate(request.plan);const primary=pid(request.plan.providerId)!;if(isCooling(primary))throw new OriginProviderError("PROVIDER_UNAVAILABLE","無料AIを現在利用できません。",503,true);const key=env.OPENROUTER_API_KEY;if(!key)throw new OriginProviderError("PROVIDER_NOT_CONFIGURED","利用可能な無料AIが設定されていません。",503,false);try{return await openrouter(request,key,fetchImpl,primary);}catch(e){if(e instanceof OriginProviderError&&e.retryable)mark(primary);if(e instanceof OriginProviderError)throw e;if(failover(e))throw e;throw new OriginProviderError("PROVIDER_INTERNAL_ERROR","無料AIとの通信に失敗しました。",503,true);}}
